Erik/logger override
phatblat/ShellExec pull request #59
Opened 2019-10-17 22:10 UTC by ErikEverson

Just some food for thought about a way to log almost all things to files as well as to Gradle

2019-11-06 03:43 UTC, phatblat requested changes
This is a great change to add "tee"-like functionality! I just have some syntax suggestions.

2019-11-06 03:43 UTC, phatblat commented on src/main/kotlin/at.phatbl.shellexec/logging/GradleLogOutputStream.kt
> +class GradleLogOutputStream(val logger: Logger, val level: LogLevel,val logFiles: Array<File>?): LogOutputStream(level.ordinal) {
Add a space after the comma. Also, add a default argument of `null` to `logFiles`, so you don't have to explicitly pass null.
```suggestion
class GradleLogOutputStream(val logger: Logger, val level: LogLevel, val logFiles: Array<File>? = null): LogOutputStream(level.ordinal) {
```

2019-11-06 03:43 UTC, phatblat commented on src/main/kotlin/at.phatbl.shellexec/ShellExec.kt
> +    var standardOutput = GradleLogOutputStream(logger, LogLevel.LIFECYCLE, null)
The `OutputStream` type is actually more important with your change to make this property writable as the caller shouldn't need to extend `GradleLogOutputStream` in order to provide a custom `OutputStream`. `null` won't be necessary here with the default argument for `logFiles` (below).

```suggestion
    var standardOutput: OutputStream = GradleLogOutputStream(logger, LogLevel.LIFECYCLE)
```

2019-11-06 03:43 UTC, phatblat commented on src/main/kotlin/at.phatbl.shellexec/ShellExec.kt
> +    var errorOutput = GradleLogOutputStream(logger, LogLevel.ERROR, null)
```suggestion
    var errorOutput: OutputStream = GradleLogOutputStream(logger, LogLevel.ERROR)
```

2019-11-06 15:02 UTC, ErikEverson commented
A note about add ing back in the outputStream as the required type. When I tested this with a composit project I get the following compile errors.

<img width="1218" alt="Screen Shot 2019-11-06 at 8 01 47 AM" src="https://user-images.githubusercontent.com/32311723/68309528-d13a9700-006b-11ea-9b49-f21456132d40.png">

2019-12-18 17:32 UTC, ErikEverson commented
@phatblat PR is ready to be looked at.

2019-12-18 23:42 UTC, phatblat approved these changes

2019-12-18 23:42 UTC, merged